schmelto/Portfolio

index.html
=> remove email check

css/styles.css, index.html
=> add projects

index.html, js/scripts.js
=> dynamic year footer

css/styles.css, index.html
add padding between sections change font size of nav fixes #31
=> style: add padding between sections

css/styles.css, index.html
=> feat: add vertificates and flex layout (#35)

index.html
=> missing brace

css/styles.css
=> fix: Change font-size property of headings  Fixes #41

index.html
=> fix: update timeline to background (#45)

index.html
=> fix: right company and university (#49)

.github/workflows/changelog.yml
=> feat: created changelog.yml file

index.html
=> fix: add icons for projects

index.html
=> fix: add alt links to img (#66)

index.html
=> fix: Links to cross-origin destinations are unsafe (#67)

css/styles.css
=> fix: Ensure text remains visible during webfont load (#69)

README.md
@schmelto I think I would like to work on the #88 for the portfolio. So far I haven't really added much, but changed what there already was. If you explain what you would like me to do please, then I would be happy to complete the changes. Thank you.
=> Improved minor changes

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
=> fix: remove triage label

.github/workflows/lighthouse.yml
=> fix: update url in lighthouse.yml

.github/workflows/lighthouse.yml
=> Update Lighthouse Check to Version 4.0.0 #110

README.md, css/styles.css
If you like it I added a custom scrollbar which matches you homepage
=> Added Custom Scroll Bar

.github/ISSUE_TEMPLATE/feature_request.yml
=> fix: change label in feature issue form

.github/ISSUE_TEMPLATE/bug_report.yml
=> fix: update bug issue form

README.md, css/styles.css, index.html, package-lock.json
resolve #121
https://cai.tools.sap/schmelto/my-first-bot/train/intents
=> feat: add chatbot

.github/workflows/lighthouse.yml
=> fix: update score

css/styles.css, js/scripts.js
=> fix: prettier issues

README.md
=> docs: add regex explanation

README.md
Took an updated GIF image of the portfolio page and added it to the README.
Fixes #138
I can see the gif is added from the assets folder of the page. Will you need it to be changed in that location as well?
=> Update Gif in README

.github/workflows/lighthouse.yml
=> fix: update lighthouse score

README.md
In the readme section
Fixes #issue
=> Updated typo

css/styles.css
=> fix: mobile view of chatbot

css/styles.css
=> feat: remove scrollbar

blog/README.md
=> docs: add readme to blog

index.html, js/scripts.js
=> fix: remove mail form

README.md
Partly fixes #178 
Typo & Grammar  in README.md
=> docs: fixed Typo & Grammar in README.md

.github/ISSUE_TEMPLATE/docs.yml
=> feat: add issue template for docs

README.md, index.html
=> docs: remove Chatbot

css/terminal.css, js/terminal.js, terminal/terminal.html
=> feat: add terminal

blog/blog.html
=> Favicon Update in blog

README.md
=> docs: added some text

css/styles.css
Reverts schmelto/Portfolio#201
=> Revert "changed card-text to white to improve contrast"

index.html
Fixes #199 - added a new card to link to the terminal
=> added new flex-card to link to terminal page

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
=> docs: remove checkbox

css/styles.css
Fixes #211.
I know you assigned yourself the task but was wondering if you'd still accept the simple changes I made to the style.css file. This should fix the CodeFactor issues.
=> Fix style issues in css #211

index.html
=> feat: add initial ogp

index.html, pages/issues.html, pages/terminal.html, reviewpad.yml
=> feat: add initial reviewpad configuration

index.html
=> alligned footer to the centre

index.html
=> fix: spelling

index.html
=> fix: Replace Twitter with X logo 

index.html
=> fix: Update profile picture and favicon

css/styles.css
=> feat: add transparency effect to the navbar

css/styles.css, package-lock.json
=> feat: add blur effect

.github/workflows/style.yml
=> feat: add prettier action

css/styles.css
=> refactor: remove unnecessary styling

js/scripts.js
=> feat: remove projects

SECURITY.md
=> chore: Update SECURITY

CODE_OF_CONDUCT.md
=> chore: Update CODE_OF_CONDUCT

index.html
=> fix: update SAP link

.github/workflows/changelog.yml
=> ci: update changelog action

.github/workflows/changelog.yml
=> fix: spelling error

README.md, package-lock.json
=> chore: Update eslint to version 9.9.1

css/styles.css
Fixes #339 
1. Added borders to the cards in the certificate section to give a professional look 
2. Added shadow effect to all the cards 
3. Added transform CSS effect that causes the cards to move in positive y direction on hover. 
4. Added appropriate margins and padding to avoid extra spaces. 
Attached a video for the reference 
https://github.com/user-attachments/assets/05034067-6319-43d4-9b23-545750dd378b
=> Modified Certificates Section

css/styles.css
=> fix: Refactor CSS styles for card hover effect
